ASoC: SOF: ipc4-topology: Fix use of uninitialized value
Initialize ref_params to zero in order to fix static analyzer
error:

ipc4-topology.c: In function ‘sof_ipc4_prepare_copier_module’:
ipc4-topology.c:1810:34: error: use of uninitialized value
‘((int *)<unknown>)[2]’ [CWE-457]
[-Werror=analyzer-use-of-uninitialized-value]
struct snd_pcm_hw_params ref_params;

Note that this is a false positive, as manually inspecting the code there
is no path where ref_params is used uninitialized.

Fixes: f9209644ae76 ("ASoC: SOF: ipc4-topology: Correct DAI copier config and NHLT blob request")
Signed-off-by: Daniel Baluta <daniel.baluta@nxp.com>