[DONOT_MERGE] fixup! UPSTREAM: ASoC: SOF: Intel: hda-mlink: Add support for mic privacy in VS SHIM registers
Patch Applicable only on v6.12
'EXPORT_SYMBOL_NS' expects namespace identifier directly,
not as a string literal.
Patch Fixes:
sound/soc/sof/intel/snd-sof-intel-hda-mlink.mod.c:49:55: error: expected ')'

Patch updates macro calls in `sound/soc/sof/intel/hda-mlink.c`
Fixes: 0978e8207b61 ("ASoC: SOF: Intel: hda-mlink: Add support for mic privacy in VS SHIM registers")

Signed-off-by: Naveen Manohar <naveen.m@intel.com>