fixup! ALSA: hda/hdmi: Add helper function to check if a device is HDMI codec
Whether patch_hdmi.c is build into the kernel is controlled by
SND_HDA_CODEC_HDMI, not SND_SOC_SOF_HDA_AUDIO_CODEC, update the if def
to check this symbol to avoid undefined function issues:

ERROR: modpost: "snd_hda_device_is_hdmi" [sound/soc/codecs/snd-soc-hdac-hda.ko] undefined!

Fixes: 5762a2e74908 ("ALSA: hda/hdmi: Add helper function to check if a device is HDMI codec")
Signed-off-by: Charles Keepax <ckeepax@opensource.cirrus.com>