ASoC: sdca: fix missing SOUNDWIRE_INTEL_FDL dependency
Fix build error when SND_SOC_SDCA_FDL is enabled:
  ERROR: modpost: "sdca_fdl_alloc_state" [sound/soc/sdca/snd-soc-sdca.ko] undefined!
  ERROR: modpost: "sdca_fdl_process" [sound/soc/sdca/snd-soc-sdca.ko] undefined!

The SDCA FDL code calls functions from SOUNDWIRE_INTEL_FDL but doesn't
select it. Add the missing select.

Fixes: upstream SOF kernel Kconfig