ASoC: SOF: Refactor nocodec handling
Fixes the following warning:
sound/soc/sof/sof-audio.c: In function ‘sof_machine_check’:

sound/soc/sof/sof-audio.c:377:1: error: label ‘nocodec’ defined but not
used [-Werror=unused-label]

Fixes: f948586b0a493e1 ("ASoC: SOF: Make creation of machine device ..")
Suggested-by: Paul Olaru <paul.olaru@nxp.com>
Signed-off-by: Daniel Baluta <daniel.baluta@nxp.com>