ASoC: SOF: fix compilation issue with readb/writeb helpers
Somehow we end-up with pre-processing issues with ARCH=arm

sound/soc/sof/ops.h: In function ‘snd_sof_dsp_writeb’:
sound/soc/sof/ops.h:309:75: error: macro "writeb" passed 3 arguments,
but takes just 2
  309 |  sof_ops(sdev)->writeb(sdev, sdev->bar[bar] + offset, value);

Rename the helpers as read8/write8 which has the added benefit of
being more consistent with read64/write64 introduced earlier for SOF.

Reported-by: Nathan Chancellor <nathan@kernel.org>
Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>