UPSTREAM: ASoC: fix build warning in soc-core.c
Fix kernel-doc build error. A symbol that ends with an underscore
character ('_') has special meaning in reST (reStructuredText), so add
a '*' to prevent this error and to indicate that there are several of
these values to choose from.

../sound/soc/soc-core.c:2799: ERROR: Unknown target name: "snd_soc_daifmt".

Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit bb19ba2a345439b4de3f6d59819da9853500ac4d)
(cherry picked from commit 6311ea0677e88d5de47e695c4d90040f13f7ce2a)
Signed-off-by: Samaga Prasanna Krishna <samaga.krishna@intel.corp-partner.google.com>

BUG=b:110025789
TEST=Test Audio use cases with full SOF 0.6 rebase release series applied.

Change-Id: I25736ef95dbce42baf570277f30a3e4f7d8cbdb0