fixup! ASoC: SOF: Convert the generic probe support to SOF client
It looks like I have missed the direct include of linux/module.h which
can cause a warning on some interesting platforms and configs, like this:

>> sound/soc/sof/intel/hda-probes.c:147:1: warning: data definition has no type or storage class
     147 | MODULE_IMPORT_NS(SND_SOC_SOF_CLIENT);
         | ^~~~~~~~~~~~~~~~
   sound/soc/sof/intel/hda-probes.c:147:1: error: type defaults to 'int' in declaration of 'MODULE_IMPORT_NS' [-Werror=implicit-int]
>> sound/soc/sof/intel/hda-probes.c:147:1: warning: parameter names (without types) in function declaration

Signed-off-by: Peter Ujfalusi <peter.ujfalusi@linux.intel.com>
Reviewed-by: Bard Liao <yung-chuan.liao@linux.intel.com>
Reviewed-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>