UPSTREAM: ALSA: fix kernel-doc build warning
Fix kernel-doc build error. A symbol that ends with an underscore
character ('_') has special meaning in reST (reStructuredText), so add
a '*' to prevent this error and to indicate that there are several of
these values to choose from.

../sound/core/jack.c:312: ERROR: Unknown target name: "snd_jack_btn".

Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
Signed-off-by: Takashi Iwai <tiwai@suse.de>
(cherry picked from commit 3f1185d6c9d3fe91aa85ec8d3f4d71207452c458)
(cherry picked from commit c790a52c68aab657e65dec041b43d9d32d976d0d)
Signed-off-by: Samaga Prasanna Krishna <samaga.krishna@intel.corp-partner.google.com>

BUG=b:110025789
TEST=Test Audio use cases with full SOF 0.6 rebase release series applied.

Change-Id: I082857b1271b71ba23301740678a9f4da867a257