fixup! ASoC: SOF: Intel: detect DMIC number in SoundWire mixed config
with allmodconfig SOF_HDA is disabled due to the exclusion with
NOCODEC but SOUNDWIRE is enabled. This can't work and leads to the
following error:

sound/soc/sof/intel/hda.c: In function ‘dmic_topology_fixup’:
sound/soc/sof/intel/hda.c:565:6: error: ‘hda_dmic_num’
undeclared (first use in this function); did you mean ‘dmic_num’?
  565 |  if (hda_dmic_num != -1) {
      |      ^~~~~~~~~~~~
      |      dmic_num

Fix by enabling the kernel parameter in the two cases where it's needed.

Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>