[DONOT_MERGE] fixup! UPSTREAM: ASoC: SOF: Intel: hda-sdw-bpt: add helpers for SoundWire BPT DMA
Patch Applicable only on v6.12
'EXPORT_SYMBOL_NS' expects namespace identifier directly,
not as a string literal.
Patch Fixes:
ERROR: modpost: module snd-sof-intel-hda-sdw-bpt uses symbol hdac_bus_eml_sdw_map_stream_ch from namespace SND_SOC_SOF_HDA_MLINK, but does not import it.
ERROR: modpost: module snd-sof-intel-hda-sdw-bpt uses symbol hda_cl_prepare from namespace SND_SOC_SOF_INTEL_HDA_COMMON, but does not import it.
ERROR: modpost: module snd-sof-intel-hda-sdw-bpt uses symbol hdac_bus_eml_sdw_get_hlink from namespace SND_SOC_SOF_HDA_MLINK, but does not import it.
ERROR: modpost: module snd-sof-intel-hda-sdw-bpt uses symbol hda_cl_cleanup from namespace SND_SOC_SOF_INTEL_HDA_COMMON, but does not import it.
ERROR: modpost: module snd-sof-intel-hda-sdw-bpt uses symbol hda_cl_trigger from namespace SND_SOC_SOF_INTEL_HDA_COMMON, but does not import it.
ERROR: modpost: module snd-sof-intel-hda-sdw-bpt uses symbol hda_dsp_stream_get_position from namespace SND_SOC_SOF_INTEL_HDA_COMMON, but does not import it.

Patch updates macro calls in `sound/soc/sof/intel/da-sdw-bpt.c`
Fixes: 5d5cb86fb46e ("ASoC: SOF: Intel: hda-sdw-bpt: add helpers for SoundWire BPT DMA")

Suggested-by: Bard Liao <yung-chuan.liao@linux.intel.com>
Signed-off-by: Naveen Manohar <naveen.m@intel.com>