[DONOT_MERGE] fixup! UPSTREAM: ASoC: SOF: Intel: mtl: Split up dsp_ops setup code
Patch Applicable only on v6.12
'EXPORT_SYMBOL_NS' expects namespace identifier directly,
not as a string literal.
Patch Fixes:
sound/soc/sof/intel/snd-sof-pci-intel-mtl.mod.c:34:37: error: expected ')'

Patch updates macro calls in `sound/soc/sof/intel/mtl.c`
Fixes: 698233342000 ("ASoC: SOF: Intel: mtl: Split up dsp_ops setup code")

Signed-off-by: Naveen Manohar <naveen.m@intel.com>