ASoC: SOF: fix nocodec handling
Fixes the warning:
sound/soc/sof/sof-audio.c: In function ‘sof_machine_check’:

sound/soc/sof/sof-audio.c:377:1: error: label ‘nocodec’ defined but not
used [-Werror=unused-label]

Fixes: f948586b0a49 ("ASoC: SOF: Make creation of machine device from SOF core optional")

Reported-by: Daniel Baluta <daniel.baluta@nxp.com>
Signed-off-by: Ranjani Sridharan <ranjani.sridharan@linux.intel.com>