UPSTREAM: ASoC: rt1320: fix 32-bit link failure
A plain 64-bit division causes a link failure in some configurations:

ERROR: modpost: "__aeabi_uldivmod" [sound/soc/codecs/snd-soc-rt1320-sdw.ko] undefined!

Since this divides by a constant, using the div_u64() macro ends up
turning this into an efficient multiply/shift operation where possible.

In rt1320_calc_r0(), the open-coded shift seems a litle simpler.

Fixes: da1682d5e8b5 ("ASoC: rt1320: support calibration and temperature/r0 loading")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://patch.msgid.link/20251223215259.677762-1-arnd@kernel.org
Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 836ecc740ca829040d86a5371f1fcb276110df84)

Test:  'tinymix 'rt1320-1 R0 Calibration' 1, check the rt1320_calibrate calibration data meet spec.
Change-Id: I1c9bcd5561240e44b22fe4678ed83b646957494d
Signed-off-by: Shuming Fan <shumingf@realtek.com>
Signed-off-by: Norman Bintang <normanbt@google.com>